# Generated by Django 3.2.7 on 2021-09-24 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_item', models.CharField(max_length=20)),
                ('ingredients', models.CharField(max_length=50)),
                ('food_process', models.TextField(max_length=20)),
            ],
        ),
    ]
