# Generated by Django 3.2.7 on 2021-10-01 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp3', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipes',
            name='recipe_Img',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
