# Generated by Django 3.2.7 on 2021-10-05 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp3', '0002_recipes_recipe_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='recipe_Img',
            field=models.ImageField(blank=True, default=0, null=True, upload_to='images/'),
        ),
    ]
