# Generated by Django 3.2.7 on 2021-10-08 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp3', '0006_rename_father_myuser_father_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='father_name',
        ),
    ]
