# Generated by Django 3.2.7 on 2021-10-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp3', '0007_remove_myuser_father_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='myuser',
            name='father_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
